# Generated by Django 3.0.7 on 2020-06-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_blogs',
            old_name='tile',
            new_name='title',
        ),
        migrations.AddField(
            model_name='all_blogs',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
